name: gert_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #  Adicione esta seção para incluir os assets
  assets:
    - assets/background.png #  Certifique-se de que o caminho está correto
  #  Se você tiver imagens em uma pasta dentro de assets, use assim:
  #  assets:
  #    - assets/images/